# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2019

# Branches to build
branches:
  only: 
    - dev


# Build matrix
environment:
  matrix:
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Chocolatey
  - choco upgrade chocolatey
  # MinGW
  - if "%type%"=="MinGW" appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.18.4/mingw/gstreamer-1.0-mingw-x86_64-1.18.4.msi
  - if "%type%"=="MinGW" appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.18.4/mingw/gstreamer-1.0-devel-mingw-x86_64-1.18.4.msi
  - if "%type%"=="MinGW" msiexec /i gstreamer-1.0-mingw-x86_64-1.18.4.msi /quiet /qn /norestart /log install-devel.log ADDLOCAL=ALL
  - if "%type%"=="MinGW" msiexec /i gstreamer-1.0-devel-mingw-x86_64-1.18.4.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
  - if "%type%"=="MinGW" set INCLUDE=C:\mingw64\x86_64-w64-mingw32\include;%INCLUDE%
  - if "%type%"=="MinGW" set LIB=C:\mingw64\x86_64-w64-mingw32\lib;%LIB%
  - if "%type%"=="MinGW" set PATH=C:\mingw64\bin;C:\gstreamer\1.0\mingw_x86_64\bin;C:\Program Files\Git\usr\bin;%PATH%
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  # Visual Studio
  - if "%type%"=="VisualStudio" appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.18.4/msvc/gstreamer-1.0-msvc-x86_64-1.18.4.msi
  - if "%type%"=="VisualStudio" appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.18.4/msvc/gstreamer-1.0-devel-msvc-x86_64-1.18.4.msi
  - if "%type%"=="VisualStudio" msiexec /i gstreamer-1.0-msvc-x86_64-1.18.4.msi /quiet /qn /norestart /log install-devel.log ADDLOCAL=ALL
  - if "%type%"=="VisualStudio" msiexec /i gstreamer-1.0-devel-msvc-x86_64-1.18.4.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL
  - if "%type%"=="VisualStudio" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%type%"=="VisualStudio" set PATH=C:\gstreamer\1.0\msvc_x86_64;C:\Program Files\Git\usr\bin;%PATH%
  # Qt
  - set QTDIR=C:\Qt\5.15.2\mingw81_64
  - set PATH=C:\Qt\5.15.2\mingw81_64\bin;C:\Qt\Tools\mingw810_64\x86_64-w64-mingw32\lib;%PATH%
  - '%command% "qmake --version"'
  # CMake
  - '%command% "cmake --version"'
  # gst
  - '%command% "gst-launch-1.0 --version"'
  # git
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - gil update
  # ehco path
  - ps: $env:path -Split ";"
  - ps: $env:include -Split ";"
  - ps: $env:lib -Split ";"
# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
